src = ["src", "tests"]
namespace-packages = ["app"]
target-version = "py311"

select = ["C", "D", "E", "F", "I", "N", "Q", "RET", "RUF", "S", "T", "UP", "YTT"]
ignore = [
    "C901",
    "E501",
    "S101",
    "N818",  # Exceptions must end with "Error" or other qualifiers (would enable, we just have some violations currently).
    "N999",  # Invalid module name, seeming false positives
]
extend-select = ["D"]
extend-ignore = [
    "D1",

    "D203",
    "D204",
    "D213",
    "D215",
    "D400",
    "D404",
    "D406",
    "D407",
    "D408",
    "D409",
    "D413",
    "C408",  # Unncessary `dict` call, we should un-ignore this
    "RET504",  # Unncessary variable assignemnt before return, we should un-ignore this
]

[pep8-naming]
classmethod-decorators = ["classmethod", "pydantic.root_validator", "pydantic.validator"]

[isort]
order-by-type = false

[per-file-ignores]
"**/tests/**/*.py" = ["D", "S", "N801", "N802", 'N806']
